[project]
name = "cadft"
version = "0.1.0"
description = "AIDFT: AI for density functional theory"

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools >= 40.6.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["cadft"]
exclude = []
namespaces = false